# -*- coding: utf-8 -*-
"""prediksisurvivaltitanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/diva-009/3478cafe5866cc000c1ed6710c44b32c/prediksisurvivaltitanic.ipynb
"""

# @title Teks judul default
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')
test_df = pd.read_csv('gender_submission.csv')

# Display the first few rows of the training data
print("Training Data Head:")
print(train_df.head())

# Get information about the training data (data types, missing values)
print("\nTraining Data Info:")
train_df.info()

# Get descriptive statistics
print("\nTraining Data Description:")
print(train_df.describe(include='all'))

# Check for missing values
print("\nMissing values in training data:")
print(train_df.isnull().sum())

# Visualize some relationships
sns.countplot(x='Survived', data=train_df)
plt.title('Survival Count (0 = No, 1 = Yes)')
plt.show()

sns.countplot(x='Survived', hue='Sex', data=train_df)
plt.title('Survival Count by Sex')
plt.show()

sns.countplot(x='Survived', hue='Pclass', data=train_df)
plt.title('Survival Count by Passenger Class')
plt.show()

sns.histplot(train_df['Age'].dropna(), kde=True)
plt.title('Age Distribution')
plt.show()

